# Definimos los servicios que vamos a tener
services:
  # Primer servicio
  proxysquid:
    # Indicamos que se debe de construir la imagen para este servicio
    build:
      # El Dockerfile se encuentra en este directorio
      context: ./proxySquid
      # Especificamos el nombre del archivo dentro del directorio (contexto)
      dockerfile: Dockerfile
    # Para que el puerto del contenedor (el que expusimos) sea accesible desde la maquina anfitriona, a esto se le llama "mapear un puerto",
    # en este caso del host al puerto del contenedor, es como si fuera un puente entre estos 2 puertos
    ports:
      - "3128:3128" # Formato PUERTO_HOST:CONTENEDOR_HOST
    # Siempre se reiniciara el contenedor si este se detiene
    restart: always
    # Ver https://shorturl.at/sI8br para mas información, lo que nos dice es:
    # "links is used to link a container to another container in the same Compose file. It creates a network connection between 
    # the linked containers, allowing them to communicate with each other." ademas de esto, se agrega por ejemplo "local.pagina1.com"
    # al directorio /etc/hosts de este contenedor. Asi que redirigimos estas solicitudes al contenedor de apache el cual ya sabe que 
    # hacer con estas solicitudes
    links:
      - "apache:local.pagina1.com"
      - "apache:local.pagina2.com"
      - "apache:local.pagina3.com"

  apache:
    # Indicamos que se debe de construir la imagen para este servicio
    build:
      # El Dockerfile se encuentra en este directorio
      context: ./virtualHostApache
      # Especificamos el nombre del archivo dentro del directorio (contexto)
      dockerfile: Dockerfile
    # Para que el puerto del contenedor (el que expusimos) sea accesible desde la maquina anfitriona, a esto se le llama "mapear un puerto",
    # en este caso del host al puerto del contenedor, es como si fuera un puente entre estos 2 puertos
    ports:
      - "80:80" # Formato PUERTO_HOST:CONTENEDOR_HOST
    # Siempre se reiniciara el contenedor si este se detiene
    restart: always