# Utilizamos la imagen de ubuntu para la creación del contenedor
FROM ubuntu:latest

# Simplemente actualizamos el contenedor e instalamos el paquete curl para hacer la prueba
RUN apt update && apt install -y curl